name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag archdental:$(date +%s)

    - name: Set up Docker authentication
      run: echo '{"auths":{"https://index.docker.io/v1/":{"auth":"$DOCKERHUB_PAT"}}}' > $HOME/.docker/config.json

    - name: Push Docker image to Docker Hub
      run: |
        docker tag archdental:$(date +%s) darrassi1/archdental:latest
        docker push darrassi1/archdental:latest
