name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'$(echo -n $DOCKER_USER:$DOCKER_PASSWORD | base64 -w 0)'"}}}' > $HOME/.docker/config.json
        cat $HOME/.docker/config.json  # Print the contents for debugging
        docker build . --file Dockerfile --tag darrassi1/archdental:$(date +%s)
        docker push darrassi1/archdental
