name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag archdental:latest

      - name: Log in to Docker Hub
        run: echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'"${{ secrets.DOCKERHUB_PAT }}"'"}}}' > $HOME/.docker/config.json

      - name: Tag Docker image
        run: docker tag archdental:latest darrassi1/archdental:latest

      - name: Push Docker image to Docker Hub
        run: docker push darrassi1/archdental:latest
